import streamlit as st
import os
import ssl
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process
from crewai_tools import TavilySearchTool, YoutubeVideoSearchTool
from pptx import Presentation
from pptx.util import Inches, Pt

# --- 1. SYSTEM CONFIGURATION ---
load_dotenv()

# Bypass SSL for NCHS Firewall
try:
    ssl._create_default_https_context = ssl._create_unverified_context
except:
    pass

os.environ["OTEL_SDK_DISABLED"] = "true"

# --- 2. THE PROCESS INTERCEPTOR ---
class StreamlitCallbackHandler:
    def __init__(self, container):
        self.container = container

    def on_step(self, step):
        """Displays agent actions and observations in real-time."""
        with self.container:
            if "Action" in str(step):
                st.markdown(f"**🤖 Agent is using tool:** `{step.tool}`")
                st.caption(f"Thought: {step.thought}")
            if hasattr(step, 'observation'):
                with st.expander("🔍 View Raw Research Data"):
                    st.write(step.observation)

# --- 3. GENS-STYLE PPT GENERATOR ---
def create_professional_ppt(ai_content, topic):
    prs = Presentation() # Use default or NCHS_Template.pptx
    
    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = topic.title()
    slide.placeholders[1].text = "NCHS Strategic Intelligence Report\nGenerated by AI Digital Department"

    # Content Slides
    sections = str(ai_content).split('##')
    for section in sections:
        if len(section.strip()) < 5: continue
        
        slide = prs.slides.add_slide(prs.slide_layouts[1]) # Title and Content
        lines = section.strip().split('\n')
        
        # Format Title
        slide.shapes.title.text = lines[0].strip()
        
        # Format Body (Bullet Points)
        body = "\n".join(lines[1:]).strip()
        tf = slide.placeholders[1].text_frame
        tf.text = body
        for p in tf.paragraphs:
            p.font.size = Pt(18)
            p.space_after = Pt(10)

    path = "NCHS_Universal_Briefing.pptx"
    prs.save(path)
    return path

# --- 4. UI SETUP ---
st.set_page_config(page_title="NCHS Universal Agent", page_icon="🧠", layout="wide")
st.title("🧠 NCHS Universal Intelligence Agent")

with st.sidebar:
    st.header("Research Parameters")
    research_topic = st.text_area("Research Objective", placeholder="e.g., Pediatric AI trends...")
    target_hospital = st.text_input("Benchmark Peers", value="CHOP, Boston Children's")
    yt_url = st.text_input("YouTube Expert Source (URL)")

# --- 5. EXECUTION ---
if st.button("🚀 Launch Research Mission"):
    if not research_topic:
        st.error("Please enter a research objective!")
    else:
        # Containers for real-time logs
        log_expander = st.expander("🕵️ Behind the Scenes: Agent Process", expanded=True)
        handler = StreamlitCallbackHandler(log_expander)

        with st.status("🤖 Digital Department is working...", expanded=True) as status:
            search_tool = TavilySearchTool()
            tools = [search_tool]
            if yt_url: tools.append(YoutubeVideoSearchTool(youtube_video_url=yt_url))

            researcher = Agent(
                role='Lead Strategic Researcher',
                goal=f'Conduct deep-dive research on: {research_topic}',
                backstory='Senior Analyst at Nicklaus Children\'s. Expert in clinical data and hospital benchmarking.',
                tools=tools, verbose=True
            )

            writer = Agent(
                role='Executive Communications Director',
                goal='Translate research into a high-level briefing.',
                backstory='Specialist in NCHS board-level communications.',
                verbose=True
            )

            task1 = Task(
                description=f"Research {research_topic} for {target_hospital}.",
                expected_output="Detailed findings with data points.",
                agent=researcher
            )

            task2 = Task(
                description=f"Draft a memo for {research_topic}. Use '##' for slide headers.",
                expected_output="Formatted markdown memo.",
                agent=writer, context=[task1]
            )

            crew = Crew(
                agents=[researcher, writer], 
                tasks=[task1, task2],
                step_callback=handler.on_step # Connects the UI to the brain
            )
            
            result = crew.kickoff()
            status.update(label="✅ Analysis Complete", state="complete")

        st.subheader("Executive Memo")
        st.markdown(result)

        ppt_path = create_professional_ppt(result, research_topic)
        with open(ppt_path, "rb") as f:
            st.download_button("📂 Download Professional Briefing", f, file_name=ppt_path)